Time: 04.07.2024 19:58:41
Error sending email to AAAAAAAAAAAAAAAAA@AAAAA.AA
Subject: Alert for Station dfhgah
Body: Station 7 reported values over range during the last 240 minutes.
Station is on dfhgah, range is 30 to 71
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

Time: 23.07.2024 22:56:59
Error sending email to AAAAAAAAAAAAAAAAA@AAAAA.AA
Subject: Alert for Station 5
Body: No report received from dfhgah, station 5 in the last 240 minutes.
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

Time: 23.07.2024 22:57:03
Error sending email to megakaktus6d@seznam.cz
Subject: Alert for Station 5
Body: No report received from dfhgah, station 5 in the last 240 minutes.
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

Time: 23.07.2024 22:57:07
Error sending email to G@G.G
Subject: Alert for Station 5
Body: No report received from dfhgah, station 5 in the last 240 minutes.
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

Time: 23.07.2024 22:57:11
Error sending email to AAAAAAAAAAAAAAAAA@AAAAA.AA
Subject: Alert for Station 6
Body: No report received from dfhgah, station 6 in the last 240 minutes.
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

Time: 23.07.2024 22:57:15
Error sending email to AAAAAAAAAAAAAAAAA@AAAAA.AA
Subject: Alert for Station 8
Body: No report received from dfhgah, station 8 in the last 240 minutes.
Exception: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (10061): Nemohlo být vytvořeno žádné připojení, protože cílový počítač je aktivně odmítl.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at SORS.Services.EmailSender.SendEmailAsync(String to, String subject, String body) in D:\dlouhyyy\gytvyhub\SORS, ze zálohy SORS se pojebal 404 AAA\gitver\SORS\SORS\Services\EmailSender.cs:line 51

